export type Page<T>={page:number;pageSize:number;total:number;items:T[]};
export type EventItem={eventId:string;type:string;receivedAt:string;deliveryId:string;status:string;attemptCount:number;endpoint:{id:string;name:string}};
export type DeadLetter={deliveryId:string;event:{id:string;type:string};endpoint:{id:string;name:string};attemptsCount:number;reason:string|null;createdAt:string;lastAttemptAt:string|null};
export type Overview={generatedAt:string;recentWindowHours:number;counts:{status:string;count:number}[];backlogReadyDue:number;deadLetterCount:number;successRate:number;failureRate:number;averageLatencyMilliseconds:number};
export type DeliveryDetail={delivery:{deliveryId:string;status:string;attemptCount:number;createdAt:string;event:{id:string;type:string;receivedAt:string};endpoint:{id:string;name:string;active:boolean}};attemptHistoryCount:number;replayHistoryCount:number;historyTruncated:boolean;attempts:{id:string;number:number;startedAt:string;completedAt:string;status:string;durationMilliseconds:number;httpStatus:number|null;errorCode:string|null}[];replays:{replayId:string;cycleNumber:number;startingAttemptNumber:number;requestedAt:string}[]};
export type Endpoint={id:string;name:string;url:string;timeoutSeconds:number;isActive:boolean;createdAt:string;updatedAt:string};
export class ApiError extends Error{constructor(message:string,public status:number,public details?:Record<string,string[]>){super(message);}}
type Fetcher=typeof fetch;
export function createApi(base=import.meta.env.VITE_API_BASE_URL??'',fetcher:Fetcher=fetch){
 const url=(path:string)=>`${base.replace(/\/$/,'')}${path}`;
 async function request<T>(path:string,init:RequestInit={}){const response=await fetcher(url(path),{...init,headers:{Accept:'application/json',...init.headers}});if(!response.ok){let p:{title?:string;detail?:string;errors?:Record<string,string[]>}={};try{p=await response.json();}catch{p={title:`Request failed (${response.status})`}}throw new ApiError(p.detail??p.title??`Request failed (${response.status})`,response.status,p.errors);}return response.status===204?undefined as T:response.json() as Promise<T>}
 const query=(values:Record<string,string|number|undefined>)=>{const q=new URLSearchParams();Object.entries(values).forEach(([k,v])=>v!==undefined&&v!==''&&q.set(k,String(v)));return q.size?`?${q}`:''};
 return {overview:(signal?:AbortSignal)=>request<Overview>('/api/operations/overview',{signal}),events:(p:{page?:number;pageSize?:number;type?:string;status?:string;endpointId?:string},signal?:AbortSignal)=>request<Page<EventItem>>('/api/events'+query(p),{signal}),delivery:(id:string,signal?:AbortSignal)=>request<DeliveryDetail>(`/api/deliveries/${id}`,{signal}),deadLetters:(page=1,signal?:AbortSignal)=>request<Page<DeadLetter>>(`/api/dead-letters?page=${page}`,{signal}),replay:(id:string)=>request<{replayId:string;deliveryId:string;status:string}>(`/api/dead-letters/${id}/replay`,{method:'POST'}),endpoints:(page=1,signal?:AbortSignal)=>request<{items:Endpoint[];page:number;pageSize:number;totalCount:number}>(`/api/endpoints?page=${page}`,{signal}),createEndpoint:(body:{name:string;url:string;timeoutSeconds:number})=>request<Endpoint&{secret:string}>('/api/endpoints/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),health:async()=>{try{return (await fetcher(url('/health/ready'),{headers:{Accept:'text/plain'}})).ok}catch{return false}}};
}
export const api=createApi();
