<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../RelayForge.Domain/RelayForge.Domain.csproj" />
    <ProjectReference Include="../RelayForge.Infrastructure/RelayForge.Infrastructure.csproj" />
  </ItemGroup>
</Project>
