// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RelayForge.Infrastructure.Persistence;

#nullable disable

namespace RelayForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RelayForgeDbContext))]
    [Migration("20260713004335_AddDeliveryReplayOperations")]
    partial class AddDeliveryReplayOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RelayForge.Domain.Endpoints.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ProtectedSecret")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("protected_secret");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_webhook_endpoints_created_id");

                    b.ToTable("webhook_endpoints", null, t =>
                        {
                            t.HasCheckConstraint("ck_webhook_endpoints_timeout", "timeout_seconds BETWEEN 1 AND 120");

                            t.HasCheckConstraint("ck_webhook_endpoints_url_scheme", "url LIKE 'http://%' OR url LIKE 'https://%'");
                        });
                });

            modelBuilder.Entity("RelayForge.Domain.Events.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("LeaseExpiresAt", "CreatedAt")
                        .HasDatabaseName("ix_deliveries_expired_leases")
                        .HasFilter("\"Status\" = 'Processing'");

                    b.HasIndex("NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("ix_deliveries_retry_due")
                        .HasFilter("\"Status\" = 'RetryScheduled'");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_deliveries_ready")
                        .HasFilter("\"Status\" IN ('Pending', 'Replayed')");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("RelayForge.Domain.Events.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ResponseSnippet")
                        .HasMaxLength(65547)
                        .HasColumnType("character varying(65547)")
                        .HasColumnName("response_snippet");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId", "Number")
                        .IsUnique();

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("RelayForge.Domain.Events.DeliveryReplay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_number");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<int>("StartingAttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("starting_attempt_number");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId", "CycleNumber")
                        .IsUnique();

                    b.ToTable("delivery_replays", (string)null);
                });

            modelBuilder.Entity("RelayForge.Domain.Events.IncomingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_incoming_events_idempotency_key");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_incoming_events_status_created");

                    b.ToTable("incoming_events", (string)null);
                });

            modelBuilder.Entity("RelayForge.Domain.Events.Delivery", b =>
                {
                    b.HasOne("RelayForge.Domain.Endpoints.WebhookEndpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RelayForge.Domain.Events.IncomingEvent", null)
                        .WithOne("Delivery")
                        .HasForeignKey("RelayForge.Domain.Events.Delivery", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelayForge.Domain.Events.DeliveryAttempt", b =>
                {
                    b.HasOne("RelayForge.Domain.Events.Delivery", null)
                        .WithMany("Attempts")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelayForge.Domain.Events.DeliveryReplay", b =>
                {
                    b.HasOne("RelayForge.Domain.Events.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelayForge.Domain.Events.IncomingEvent", b =>
                {
                    b.HasOne("RelayForge.Domain.Endpoints.WebhookEndpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RelayForge.Domain.Events.Delivery", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("RelayForge.Domain.Events.IncomingEvent", b =>
                {
                    b.Navigation("Delivery")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
